version: '3'
services:
  mysql:
    image: 'mysql'
    ports:
      - "3307:3306"
    container_name: 'typeorm-issue-mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=testIssue
      - MYSQL_DATABASE=testDb
